### ISSUE TITLE
Copr build failed(timeout)

### ISSUE THREAD

**Issue by jonas2515** [biswasab/chromium_vaapi_fed#1]
Seems like the builds for copr have all failed, any idea what's wrong there?

**Comment by qnixsynapse** [comment]
Build time. It's taking too much time to compile. That's why I uploaded binaries here.

**Comment by jonas2515** [comment]
Hmm okay I understand, thanks for the effort of collecting the patches and sharing the binaries. I'd suggest leaving this issue open for visibility but feel free to close it if you want :)

**Comment by qnixsynapse** [comment]
I will keep this issue open until It get fixed. If anyone can suggest me how to speed up build process in Fedora copr to help me fix this. Right now I am trying to patch the "Official clean version". The offficial version is still at version 63.

**Comment by qnixsynapse** [comment]
Hopefully It is fixed. Won't close this issue until tomorrow. Removed building of headless to save time.
