### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by chimzycash** [biswasab/chromium_vaapi_fed#10]
Hi...
Came across your awesome project. I'm Chimzy, and I'm basically a logo/designer who loves to help contribute to amazing open source projects. I saw your project and I want to help create a unique logo/icon that will represent your project and give it a unique identity.

Working on a logo design idea concept that i feel you might like... I will share it here once i complete it, so you can give your feedback on any changes you might want.

your response will be greatly appreciated.

Regards!

**Comment by qnixsynapse** [comment]
Thanks alot for the offer but I don't thing a new logo is required for this. This is a fork of Chromium browser with out of tree patches for video acceleration support on Linux. There is no need of transforming it to a separate project as of now and thus no need of new logo design(logos are provided by the upstream).


Hence closing.
Regards.
