### ISSUE TITLE
chromium-vaapi

### ISSUE THREAD

**Issue by mcodyre** [biswasab/chromium_vaapi_fed#13]
Steps to reproduce the problem:
1.open browser
2.wait a couple of hours
3.see attached jpeg

What is the expected behaviour?
it doesn't attempt to auto update
![chromium_update](https://user-images.githubusercontent.com/17486968/66131993-5bea2b00-e5c2-11e9-94db-aafe252d21eb.jpg)

_What went wrong?_
it attempts to auto update and the device is running in kiosk mode without user interaction to remedy the issue (not using the kiosk switch just full screening the window)

_Did this work before?_ Yes 73.x.xxxx

_Does this work in other browsers?_ No
 Chromium-vaapi auto update attempts to run in Linux on version 76.0.3809.132 as well

Chrome version: Chromium-vaapi 75.0.3770.142  Channel: n/a
OS Version: fedora core 29
Flash Version: none

_Things we have tried so far:_

We have set:
"DeviceAutoUpdateDisabled": true,

In a policies file in /etc/chromium/policies/managed/engine.json.  Although it still prompts an update.

We are going to try today:
Install chromium-vaapi fresh without an active network connection to see if this occurs.

I have created a firewall that blocks all outgoing traffic although it still gets into this state.  I believe chromium may be keeping a file that indicates that it needs to update that it pulled from the network.   We use a new random user directory every time chromium starts so I'm not sure how it would hold state.  --user-data-dir=/

I've attached an image of what we are seeing.

Thanks

Mark

**Comment by qnixsynapse** [comment]
I have personally yet to encounter this bug but since this bug is been reported in Redhat [Bugzilla](https://bugzilla.redhat.com/show_bug.cgi?id=1745745) as well, I need to investigate this.

**Comment by qnixsynapse** [comment]
Upstream report: https://bugs.chromium.org/p/chromium/issues/detail?id=1010592&q=chromium%20on%20linux%20auto%20update&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified

**Comment by qnixsynapse** [comment]
Fixed upstream. Closing this.
