### ISSUE TITLE
Use some new flags

### ISSUE THREAD

**Issue by mthomos** [biswasab/chromium_vaapi_fed#16]
For better compatibility and optimization

enable_nacl_nonsfi=false
enable_vr=false
is_cfi=true
use_thin_lto=true

**Comment by qnixsynapse** [comment]
Okay, But I have heard that lto has serious problem on GCC. But I will try the rest of them including disabling VR.

**Comment by sheepdestroyer** [comment]
no vr? not fun...

**Comment by qnixsynapse** [comment]
@sheepdestroyer  Do you use VR?

**Comment by sheepdestroyer** [comment]
Yes, I have an Index. Firefox Reality is doing fun stuffs, and Chrome 79 beta also just added WebXR support. So great things are coming this way.

**Comment by qnixsynapse** [comment]
@sheepdestroyer I will re-enable it on future version. The other flag op mentioned works only on clang.

For optimisation, I'm using Redhat build flags. 
Anyways, closing this. Please reopen if there are any more flags independent of the compiler chosen.
