### ISSUE TITLE
Native Client

### ISSUE THREAD

**Issue by ghost** [biswasab/chromium_vaapi_fed#2]
This build lacks native client patch. I need it for Moonlight for Chrome. I don't mind helping if you don't want to do it.

**Comment by qnixsynapse** [comment]
I actually turned off nacl because webAssembly is around the corner.  I won't mind turning on pnacl if moonlight requires it. Please tell it's devs to move to webassembly because sooner or later google will kill it.

**Comment by ghost** [comment]
I contacted them, but I didn't realize how bad Google is about Linux support. Sucks that we have to patch Chromium to get basic Hardware Acceleration.

**Comment by qnixsynapse** [comment]
You're correct. Okay. But i need a powerful "free" builder capable of compiling chromium with nacl support.  I will try it on obs though.

**Comment by qnixsynapse** [comment]
The latest build with nacl support failed in copr. If you can help me fix that, please do a pull request. Thank you. Closing :)
