### ISSUE TITLE
Patch for Chromium 72

### ISSUE THREAD

**Issue by paulmenzel** [biswasab/chromium_vaapi_fed#8]
Is there already an updated patch – maybe WIP – for Chromium 72?

**Comment by qnixsynapse** [comment]
@paulmenzel [here](https://pkgs.rpmfusion.org/cgit/free/chromium-vaapi.git/tree/enable-vaapi.patch).

I don't update this repo anymore. My patch is used by Ubuntu snap, Arch Linux and Fedora. You can also get from there as well.
